version: "3.9"

services:
  backend:
    build: .
    container_name: time-backend
    restart: always
    env_file:
      - backend/.env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
